name: auvnet
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch=1.11.0
  - torchvision=0.12.0
  - cudatoolkit=11.3
  - scipy=1.6.0
  - scikit-image=0.19.0
  - scikit-learn=0.24.2
  - h5py=3.3.0
  - Cython=0.29.21
  - pip=20.3.3
  - pip:
    - PyMCubes==0.1.2
    - opencv-python
    - open3d==0.13.0